USE [master]
GO
/****** Object:  Database [tiendaBD]    Script Date: 25/9/2023 10:05:02 ******/
CREATE DATABASE [tiendaBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tiendaBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tiendaBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tiendaBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tiendaBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [tiendaBD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tiendaBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [tiendaBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tiendaBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tiendaBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tiendaBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tiendaBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [tiendaBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [tiendaBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tiendaBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tiendaBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tiendaBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tiendaBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tiendaBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tiendaBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tiendaBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tiendaBD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [tiendaBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tiendaBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tiendaBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [tiendaBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [tiendaBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tiendaBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tiendaBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [tiendaBD] SET RECOVERY FULL 
GO
ALTER DATABASE [tiendaBD] SET  MULTI_USER 
GO
ALTER DATABASE [tiendaBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tiendaBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [tiendaBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [tiendaBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [tiendaBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [tiendaBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'tiendaBD', N'ON'
GO
ALTER DATABASE [tiendaBD] SET QUERY_STORE = OFF
GO
USE [tiendaBD]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 25/9/2023 10:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Fechacreado] [date] NULL,
	[Estado] [int] NOT NULL,
 CONSTRAINT [PK_Categorias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 25/9/2023 10:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Correo] [varchar](100) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
	[Genero] [char](1) NOT NULL,
	[Fechacreado] [date] NULL,
	[Estado] [int] NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DetallesPedidos]    Script Date: 25/9/2023 10:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DetallesPedidos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Idpedido] [int] NULL,
	[Idproducto] [int] NOT NULL,
	[Valor] [decimal](18, 2) NULL,
	[Cantidad] [int] NULL,
	[Valortotal] [decimal](18, 2) NULL,
 CONSTRAINT [PK_DetallesPedidos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedidos]    Script Date: 25/9/2023 10:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedidos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [date] NOT NULL,
	[Idcliente] [int] NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Pedidos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 25/9/2023 10:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Idcategoria] [int] NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Imagen] [varbinary](max) NULL,
	[Precioventa] [decimal](18, 2) NOT NULL,
	[Descripcion] [text] NULL,
	[Fechacreacion] [date] NULL,
	[Fechaactuailizacion] [date] NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DetallesPedidos]  WITH CHECK ADD  CONSTRAINT [FK_DetallesPedidos_Pedidos] FOREIGN KEY([Idpedido])
REFERENCES [dbo].[Pedidos] ([Id])
GO
ALTER TABLE [dbo].[DetallesPedidos] CHECK CONSTRAINT [FK_DetallesPedidos_Pedidos]
GO
ALTER TABLE [dbo].[DetallesPedidos]  WITH CHECK ADD  CONSTRAINT [FK_DetallesPedidos_Productos] FOREIGN KEY([Idproducto])
REFERENCES [dbo].[Productos] ([Id])
GO
ALTER TABLE [dbo].[DetallesPedidos] CHECK CONSTRAINT [FK_DetallesPedidos_Productos]
GO
ALTER TABLE [dbo].[Pedidos]  WITH CHECK ADD  CONSTRAINT [FK_Pedidos_Clientes] FOREIGN KEY([Idcliente])
REFERENCES [dbo].[Clientes] ([Id])
GO
ALTER TABLE [dbo].[Pedidos] CHECK CONSTRAINT [FK_Pedidos_Clientes]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Categorias] FOREIGN KEY([Idcategoria])
REFERENCES [dbo].[Categorias] ([Id])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Categorias]
GO
USE [master]
GO
ALTER DATABASE [tiendaBD] SET  READ_WRITE 
GO
